language: node_js       #javascript
node_js:
  - stable

env:
  - DEPLOY_FOLDER=deploy
 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  local-dir: $DEPLOY_FOLDER
  keep-history: true
  on:
    branch: master

cache:
  directories:
    - node_modules

install:
  - npm install -g json-minify
    
script:
  - node ./build-ci/test.js ./recipes.json
  
after_success:
  - mkdir $DEPLOY_FOLDER
  - cp recipes.json $DEPLOY_FOLDER
  - cp index.html $DEPLOY_FOLDER
  - cp LICENSE $DEPLOY_FOLDER
  - cp README.md $DEPLOY_FOLDER
  - node ./build-ci/build_dictionary.js ./recipes.json ./recipes.dictionary.json
  - cp ./recipes.dictionary.json $DEPLOY_FOLDER/recipes.dictionary.json
  - json-minify ./recipes.json > $DEPLOY_FOLDER/recipes.min.json
  - json-minify ./recipes.dictionary.json > $DEPLOY_FOLDER/recipes.dictionary.min.json