language: node_js       #javascript
node_js:
  - "iojs"
  - "7"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master

script:
  - node ./test/test.js
  
