language: node_js       #javascript
node_js:
  - stable

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master

cache:
  directories:
    - node_modules

install:
  - npm install -g json-minify
    
script:
  - node ./build-ci/test.js ./recipes.json
  
after_success:
  - node ./build-ci/build_dictionary.js ./recipes.json ./recipes.dictionary.json
  - json-minify ./recipes.json > recipes.min.json
  - json-minify ./recipes.dictionary.json > recipes.dictionary.min.json
  - rm .travis.yml
  - rm .gitattributes
  - rm -rf test
